fixtures
fix


fix


fix


fix

diff --git a/docker/php/Dockerfile b/docker/php/Dockerfile
--- a/docker/php/Dockerfile
+++ b/docker/php/Dockerfile
@@ -1,7 +1,10 @@
 # docker/php/Dockerfile
 FROM php:8.2-fpm-alpine
 
-WORKDIR /var/www/symfony
+
+ARG UID=82
+ARG GID=82
+
 
 RUN apk add --no-cache \
     icu-dev \
@@ -10,8 +13,28 @@ RUN apk add --no-cache \
     libxml2-dev \
     oniguruma-dev \
     git \
-    unzip
+    unzip \
+    shadow \
+    su-exec
 
+RUN \
+    if ! getent group www-data > /dev/null; then \
+        echo "Group www-data not found, creating with GID $GID..."; \
+        addgroup -g $GID -S www-data; \
+    elif [ "$(getent group www-data | cut -d: -f3)" != "$GID" ]; then \
+        echo "Group www-data exists, changing GID to $GID..."; \
+
+        delgroup www-data && addgroup -g $GID -S www-data || groupmod -g $GID www-data ; \
+    fi && \
+    \
+    if ! getent passwd www-data > /dev/null; then \
+        echo "User www-data not found, creating with UID $UID and GID $GID..."; \
+        adduser -u $UID -D -S -G www-data www-data -s /sbin/nologin; \
+    elif [ "$(getent passwd www-data | cut -d: -f3)" != "$UID" ] || [ "$(getent passwd www-data | cut -d: -f4)" != "$GID" ]; then \
+        echo "User www-data exists, changing UID to $UID and GID to $GID..."; \
+        usermod -u $UID -g $GID www-data; \
+    fi && \
+    echo "www-data UID is now $(id -u www-data) and GID is $(id -g www-data)"
 
 RUN docker-php-ext-install -j$(nproc) \
     intl \
@@ -22,13 +45,11 @@ RUN docker-php-ext-install -j$(nproc) \
     xml \
     mbstring
 
+WORKDIR /var/www/symfony
+
 
 COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
 
-
-RUN if ! getent group www-data > /dev/null; then \
-        addgroup -g 82 -S www-data; \
-    fi && \
-    if ! getent passwd www-data > /dev/null; then \
-        adduser -u 82 -D -S -G www-data www-data -s /sbin/nologin; \
-    fi
+RUN mkdir -p var/cache var/log && \
+    chown -R www-data:www-data var && \
+    chmod -R 775 var 
